// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// stiagent_runsim
List stiagent_runsim(List params);
RcppExport SEXP stiagent_stiagent_runsim(SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type params(paramsSEXP);
    __result = Rcpp::wrap(stiagent_runsim(params));
    return __result;
END_RCPP
}
// stiagent_comp_interv
List stiagent_comp_interv(List params);
RcppExport SEXP stiagent_stiagent_comp_interv(SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type params(paramsSEXP);
    __result = Rcpp::wrap(stiagent_comp_interv(params));
    return __result;
END_RCPP
}
