# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

stiagent_runsim <- function(params) {
    .Call('stiagent_stiagent_runsim', PACKAGE = 'stiagent', params)
}

stiagent_comp_interv <- function(params) {
    .Call('stiagent_stiagent_comp_interv', PACKAGE = 'stiagent', params)
}

